export { default as Navigation } from './Navigation';
export { default as Hero } from './Hero';
export { default as Services } from './Services';
export { default as Portfolio } from './Portfolio';
export { default as Team } from './Team';
export { default as Testimonials } from './Testimonials';
export { default as Pricing } from './Pricing';
export { default as Contact } from './Contact';
export { default as Footer } from './Footer';
